### ISSUE TITLE
Tag with this name not found: EXT-X-ALLOW-CACHE

### ISSUE THREAD

**Issue by kaisersakhi** [selsta/hlsdl#74]
May 01, 2020 3:48:16 PM org.fbk.cit.hlt.parsers.hls.StreamManager info
INFO: [radioKashmir] Starting handling stream
May 01, 2020 3:48:16 PM org.reflections.Reflections scan
INFO: Reflections took 118 ms to scan 1 urls, producing 8 keys and 34 values 
May 01, 2020 3:48:16 PM org.fbk.cit.hlt.parsers.hls.tags.TagFactory buildTags
INFO: Building tags. Found 13 tags
org.fbk.cit.hlt.parsers.hls.exceptions.InvalidTagString: Tag with this name not found: EXT-X-ALLOW-CACHE
	at org.fbk.cit.hlt.parsers.hls.tags.TagFactory.getTag(TagFactory.java:45)
	at org.fbk.cit.hlt.parsers.hls.PlaylistParser.parse(PlaylistParser.java:59)
	at org.fbk.cit.hlt.parsers.hls.PlaylistParser.parseTwitchMaster(PlaylistParser.java:43)
	at org.fbk.cit.hlt.parsers.hls.StreamManager.onFinish(StreamManager.java:218)
	at org.fbk.cit.hlt.parsers.hls.download.SimpleDownloader.resolve(SimpleDownloader.java:60)
	at org.fbk.cit.hlt.parsers.hls.download.SimpleDownloader.download(SimpleDownloader.java:52)
	at org.fbk.cit.hlt.parsers.hls.StreamManager.submitJob(StreamManager.java:199)
	at org.fbk.cit.hlt.parsers.hls.StreamManager.submitJob(StreamManager.java:193)
	at org.fbk.cit.hlt.parsers.hls.StreamManager.start(StreamManager.java:72)
	at org.fbk.cit.hlt.parsers.hls.StreamManager.main(StreamManager.java:335)
May 01, 2020 3:48:16 PM org.fbk.cit.hlt.parsers.hls.StreamManager warn
INFO: [radio] Parsing failed for Master Playlist
May 01, 2020 3:48:16 PM org.fbk.cit.hlt.parsers.hls.StreamManager warn
INFO: [radio] Master Playlist haven't been downloaded. Halting

**Comment by selsta** [comment]
wrong repo
